### ISSUE TITLE
Unable to run : No module named data_utils

### ISSUE THREAD

**Issue by parvathysarat** [easonnie/semanticRetrievalMRS#12]
Hi, is there any major setup step that I may have missed? I can see that others have successfully ran your code but I'm not able to import the modules from ```src``` folder. Is this an issue anybody has ran into?
```setup.sh``` should be setting the root directories and I do not need to add my path to it right?
Thanks in advance, much appreciated!

**Comment by parvathysarat** [comment]
Issue fixed.
The setup.sh was not running since I hadn't set up bash, manually added the paths :)

**Comment by RishabhMaheshwary** [comment]
@parvathysarat How did you run it?
