### ISSUE TITLE
Is it fine to use a newer version torch and allennlp?

### ISSUE THREAD

**Issue by nasyxx** [easonnie/semanticRetrievalMRS#4]
Can I use the latest torch and allennlp?

Will it be any differents between the results?

**Comment by easonnie** [comment]
In general, it should be fine. You can try to run the script with the latest version and then you might need to make some changes according to the version-compatibility-related-errors or warnings. There might be minor difference on the results but not in a way that would affect any conclusions.

**Comment by nasyxx** [comment]
Thank you.
